### ISSUE TITLE
Message Template

### ISSUE THREAD

**Issue by TylerRose** [Philter-Non-Profit/Aura#21]
Create a template to hold common messages. Allow these to be sent by the MessagingService.

**Comment by akm3** [comment]
Twilio wants this information on our campaign
https://support.twilio.com/hc/en-us/articles/11847054539547-A2P-10DLC-Campaign-Approval-Requirements


Create new A2P Campaign

A Campaign represents your messaging use case with Twilio, for example, sending account notifications or conducting marketing. Every campaign is connected to a registered A2P Brand and a Messaging Service. Once successfully registered, you will be able to associate your 10DLC numbers with the connected Messaging Service to avail A2P Messaging benefits and avoid any carrier penalties for unregistered messaging. [Read more](https://www.twilio.com/docs/messaging/services/api/us-a2p-campaign-resource)


A2P Brand





Available A2P Campaign use cases





Learn more

(required)
Messaging Service
Campaign will be linked to selected Messaging Service. 10DLC Phone numbers can be added to the Messaging Service after Campaign has been created.

Create new Messaging Service
Messaging Service will be created automatically with Campaign registration.

Select existing Messaging Service

(information)
Please do not include any [Personal Identifiable Information (PII)](https://www.dol.gov/general/ppii)

 in Campaign registration fields
Publicly available information like brand names and phone numbers is acceptable. [Learn more about best practices](https://support.twilio.com/hc/en-us/articles/11847054539547-A2P-10DLC-Campaign-Approval-Best-Practices)

Campaign description

Describe what you will be using this campaign for. 
Learn more
Sample message #1

Provide an example of a message that you will be sending with this campaign. This message sample will be used by carriers to help identify your traffic. 
Learn more
Sample message #2

Provide an example of a message that you will be sending with this campaign. This message sample will be used by carriers to help identify your traffic.
Message contents
Messages will include embedded links.
Messages will include phone numbers.

(information)
Did you know?
Most Campaigns that fail or are rejected are due to incorrect information being submitted in the "How do end-users consent to receive messages?" section below. 
Learn more
How do end-users consent to receive messages? (40-2048 characters)

This field should describe how end users opt-in to the campaign, therefore giving consent to the sender to receive their messages. If multiple opt-in methods can be used for the same campaign, they must all be listed. 
Learn more
Opt-in Keywords (max 255 characters)

If end users can text in a keyword (for example, “Subscribe”) to start receiving messages from your campaign, those keywords must be provided. If you do not support opt-in via text, please leave this blank. 
Learn more
Press Delete or Backspace to remove. Press Enter to toggle selection.
Opt-in Message (20-320 characters)

If end users can text in a keyword to start receiving messages from your campaign, the auto-reply messages sent to the end users must be provided. The opt-in response should include the Brand name, confirmation of opt-in enrollment to a recurring message campaign, how to get help, and clear description of how to opt-out. If you do not support opt-in via text, please leave this blank. 
Learn more
